@extends('layouts.app')
@section('title', 'Welcome to Arzavo - Educational Management Platform')
@section('content')
@include('arzavo.website.partials.navbar')
@include('arzavo.website.home.partials.hero')
@include('arzavo.website.home.partials.why-arzavo')
@include('arzavo.website.home.partials.features')
@include('arzavo.website.home.partials.comparison')
@include('arzavo.website.home.partials.how-it-works')
@include('arzavo.website.home.partials.use-cases')
@include('arzavo.website.home.partials.testimonials')
@include('arzavo.website.home.partials.pricing')
@include('arzavo.website.home.partials.faq')
@include('arzavo.website.home.partials.documentation')
@include('arzavo.website.partials.footer')
@endsection
