<?php

return [
    "none",
    
    "school",
    "graduation-cap",
    "chalkboard",
    "chalkboard-user",
    "users",
    "user",
    "user-graduate",
    "user-group",
    "user-tie",
    "user-gear",
    "user-check",
    "user-edit",
    "user-plus",
    "user-minus",
    "id-card",
    "id-badge",

    "book",
    "book-open",
    "book-atlas",
    "book-bookmark",
    "bookmark",
    "books",
    "folder",
    "folder-open",
    "file",
    "file-lines",
    "file-pen",
    "file-circle-check",
    "file-circle-exclamation",
    "file-invoice",
    "file-contract",

    "calendar",
    "calendar-days",
    "calendar-check",
    "calendar-week",
    "clock",
    "hourglass",
    "stopwatch",

    "clipboard",
    "clipboard-check",
    "clipboard-list",
    "pen",
    "pen-to-square",
    "edit",
    "pencil",

    "chart-bar",
    "chart-line",
    "chart-pie",
    "diagram-project",
    "diagram-successor",

    "money-bill",
    "money-bill-1",
    "credit-card",
    "wallet",
    "receipt",
    "percent",
    "indian-rupee-sign",
    "sack-dollar",
    "circle-dollar-to-slot",

    "building",
    "building-columns",
    "landmark",
    "city",

    "house",
    "house-user",
    "warehouse",

    "cog",
    "gears",
    "wrench",
    "tools",
    "sliders",
    "toggle-on",
    "toggle-off",

    "bell",
    "bullhorn",
    "envelope",
    "envelope-open",
    "inbox",
    "phone",
    "phone-alt",
    "mobile-alt",

    "comment",
    "comments",
    "message",
    "message-lines",

    "search",
    "search-plus",
    "search-minus",

    "table",
    "table-cells",
    "table-list",
    "th",
    "list",
    "list-check",

    "arrow-right",
    "arrow-left",
    "arrow-up",
    "arrow-down",
    "angle-right",
    "angle-left",
    "angles-right",
    "angles-left",
    "angles-up",
    "angles-down",

    "upload",
    "download",
    "cloud-upload-alt",
    "cloud-download-alt",

    "print",
    "qrcode",
    "barcode",

    "lock",
    "unlock",
    "shield",
    "shield-halved",
    "key",

    "wifi",
    "server",
    "database",
    "laptop",
    "desktop",
    "mobile",
    "keyboard",
    "mouse",

    "map",
    "location-dot",
    "location-pin",
    "map-marker-alt",
    "route",
    "bus",
    "car",

    "medal",
    "trophy",
    "star",
    "heart",

    "check",
    "check-circle",
    "circle-check",
    "square-check",
    "square-xmark",
    "circle-xmark",
    "exclamation-circle",
    "circle-info",
    "question-circle",

    "recycle",
    "sync",
    "rotate-right",

    "globe",
    "language",
    "flag",

    "sun",
    "moon",
    "leaf",

    "trash",
    "trash-can",
    "ban",

    "plus",
    "minus",
    "xmark",
];
