@extends('layouts.app')
@section('title', 'Welcome to Arzavo - Educational Management Platform')
@section('content')
@include('arzavo.partials.navbar')
@include('arzavo.home.partials.hero')
@include('arzavo.home.partials.features')
@include('arzavo.home.partials.how-it-works')
@include('arzavo.home.partials.use-cases')
@include('arzavo.home.partials.testimonials')
@include('arzavo.home.partials.pricing')
@include('arzavo.home.partials.documentation')
@include('arzavo.partials.footer')
@endsection